name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review, milestone]

jobs:
  add-assigner:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-preencher assigner
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: '.github/auto_assign.yml' # Only needed if you use something other than .github/auto_assign.yml


  check-milestone:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar Milestone
      run: |
        npm install @octokit/rest@18.0.0
        node - <<EOF
          const { Octokit } = require("@octokit/rest");
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

          const { data: milestones } = await octokit.request('GET /repos/{owner}/{repo}/milestones', {
            owner: "${{ github.repository_owner }}",
            repo: "${{ github.repository }}",
            state: "open"
          });

          if (milestones.length > 0) {
            console.log("Existe pelo menos uma milestone definida.");
          } else {
            console.log("Nenhuma milestone definida.");
          }
        EOF